package com.hotien.service.mapper;

import com.hotien.service.po.CuishouTask;
import com.hotien.service.po.CuishouTaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CuishouTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_task
     *
     * @mbggenerated Fri Apr 07 14:33:12 CST 2017
     */
    int countByExample(CuishouTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_task
     *
     * @mbggenerated Fri Apr 07 14:33:12 CST 2017
     */
    int deleteByExample(CuishouTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_task
     *
     * @mbggenerated Fri Apr 07 14:33:12 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_task
     *
     * @mbggenerated Fri Apr 07 14:33:12 CST 2017
     */
    int insert(CuishouTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_task
     *
     * @mbggenerated Fri Apr 07 14:33:12 CST 2017
     */
    int insertSelective(CuishouTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_task
     *
     * @mbggenerated Fri Apr 07 14:33:12 CST 2017
     */
    List<CuishouTask> selectByExample(CuishouTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_task
     *
     * @mbggenerated Fri Apr 07 14:33:12 CST 2017
     */
    CuishouTask selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_task
     *
     * @mbggenerated Fri Apr 07 14:33:12 CST 2017
     */
    int updateByExampleSelective(@Param("record") CuishouTask record, @Param("example") CuishouTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_task
     *
     * @mbggenerated Fri Apr 07 14:33:12 CST 2017
     */
    int updateByExample(@Param("record") CuishouTask record, @Param("example") CuishouTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_task
     *
     * @mbggenerated Fri Apr 07 14:33:12 CST 2017
     */
    int updateByPrimaryKeySelective(CuishouTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_task
     *
     * @mbggenerated Fri Apr 07 14:33:12 CST 2017
     */
    int updateByPrimaryKey(CuishouTask record);
}