package com.hotien.service.mapper;

import com.hotien.service.po.CuishouUserOverdue;
import com.hotien.service.po.CuishouUserOverdueExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CuishouUserOverdueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_user_overdue
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    int countByExample(CuishouUserOverdueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_user_overdue
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    int deleteByExample(CuishouUserOverdueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_user_overdue
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_user_overdue
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    int insert(CuishouUserOverdue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_user_overdue
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    int insertSelective(CuishouUserOverdue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_user_overdue
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    List<CuishouUserOverdue> selectByExample(CuishouUserOverdueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_user_overdue
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    CuishouUserOverdue selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_user_overdue
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    int updateByExampleSelective(@Param("record") CuishouUserOverdue record, @Param("example") CuishouUserOverdueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_user_overdue
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    int updateByExample(@Param("record") CuishouUserOverdue record, @Param("example") CuishouUserOverdueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_user_overdue
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    int updateByPrimaryKeySelective(CuishouUserOverdue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_user_overdue
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    int updateByPrimaryKey(CuishouUserOverdue record);
}