package com.hotien.service.mapper;

import com.hotien.service.po.CuishouTaskAssign;
import com.hotien.service.po.CuishouTaskAssignExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CuishouTaskAssignMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_task_assign
     *
     * @mbggenerated Fri Apr 07 14:35:03 CST 2017
     */
    int countByExample(CuishouTaskAssignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_task_assign
     *
     * @mbggenerated Fri Apr 07 14:35:03 CST 2017
     */
    int deleteByExample(CuishouTaskAssignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_task_assign
     *
     * @mbggenerated Fri Apr 07 14:35:03 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_task_assign
     *
     * @mbggenerated Fri Apr 07 14:35:03 CST 2017
     */
    int insert(CuishouTaskAssign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_task_assign
     *
     * @mbggenerated Fri Apr 07 14:35:03 CST 2017
     */
    int insertSelective(CuishouTaskAssign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_task_assign
     *
     * @mbggenerated Fri Apr 07 14:35:03 CST 2017
     */
    List<CuishouTaskAssign> selectByExample(CuishouTaskAssignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_task_assign
     *
     * @mbggenerated Fri Apr 07 14:35:03 CST 2017
     */
    CuishouTaskAssign selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_task_assign
     *
     * @mbggenerated Fri Apr 07 14:35:03 CST 2017
     */
    int updateByExampleSelective(@Param("record") CuishouTaskAssign record, @Param("example") CuishouTaskAssignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_task_assign
     *
     * @mbggenerated Fri Apr 07 14:35:03 CST 2017
     */
    int updateByExample(@Param("record") CuishouTaskAssign record, @Param("example") CuishouTaskAssignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_task_assign
     *
     * @mbggenerated Fri Apr 07 14:35:03 CST 2017
     */
    int updateByPrimaryKeySelective(CuishouTaskAssign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_task_assign
     *
     * @mbggenerated Fri Apr 07 14:35:03 CST 2017
     */
    int updateByPrimaryKey(CuishouTaskAssign record);
}