package com.hotien.service.mapper;

import com.hotien.service.po.CuishouTaskRecord;
import com.hotien.service.po.CuishouTaskRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CuishouTaskRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_task_record
     *
     * @mbggenerated Fri Apr 07 14:35:15 CST 2017
     */
    int countByExample(CuishouTaskRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_task_record
     *
     * @mbggenerated Fri Apr 07 14:35:15 CST 2017
     */
    int deleteByExample(CuishouTaskRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_task_record
     *
     * @mbggenerated Fri Apr 07 14:35:15 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_task_record
     *
     * @mbggenerated Fri Apr 07 14:35:15 CST 2017
     */
    int insert(CuishouTaskRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_task_record
     *
     * @mbggenerated Fri Apr 07 14:35:15 CST 2017
     */
    int insertSelective(CuishouTaskRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_task_record
     *
     * @mbggenerated Fri Apr 07 14:35:15 CST 2017
     */
    List<CuishouTaskRecord> selectByExample(CuishouTaskRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_task_record
     *
     * @mbggenerated Fri Apr 07 14:35:15 CST 2017
     */
    CuishouTaskRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_task_record
     *
     * @mbggenerated Fri Apr 07 14:35:15 CST 2017
     */
    int updateByExampleSelective(@Param("record") CuishouTaskRecord record, @Param("example") CuishouTaskRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_task_record
     *
     * @mbggenerated Fri Apr 07 14:35:15 CST 2017
     */
    int updateByExample(@Param("record") CuishouTaskRecord record, @Param("example") CuishouTaskRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_task_record
     *
     * @mbggenerated Fri Apr 07 14:35:15 CST 2017
     */
    int updateByPrimaryKeySelective(CuishouTaskRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_task_record
     *
     * @mbggenerated Fri Apr 07 14:35:15 CST 2017
     */
    int updateByPrimaryKey(CuishouTaskRecord record);
}