package com.hotien.service.mapper;

import com.hotien.service.po.CuishouEmployee;
import com.hotien.service.po.CuishouEmployeeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CuishouEmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_employee
     *
     * @mbggenerated Fri Apr 07 14:34:48 CST 2017
     */
    int countByExample(CuishouEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_employee
     *
     * @mbggenerated Fri Apr 07 14:34:48 CST 2017
     */
    int deleteByExample(CuishouEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_employee
     *
     * @mbggenerated Fri Apr 07 14:34:48 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_employee
     *
     * @mbggenerated Fri Apr 07 14:34:48 CST 2017
     */
    int insert(CuishouEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_employee
     *
     * @mbggenerated Fri Apr 07 14:34:48 CST 2017
     */
    int insertSelective(CuishouEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_employee
     *
     * @mbggenerated Fri Apr 07 14:34:48 CST 2017
     */
    List<CuishouEmployee> selectByExample(CuishouEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_employee
     *
     * @mbggenerated Fri Apr 07 14:34:48 CST 2017
     */
    CuishouEmployee selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_employee
     *
     * @mbggenerated Fri Apr 07 14:34:48 CST 2017
     */
    int updateByExampleSelective(@Param("record") CuishouEmployee record, @Param("example") CuishouEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_employee
     *
     * @mbggenerated Fri Apr 07 14:34:48 CST 2017
     */
    int updateByExample(@Param("record") CuishouEmployee record, @Param("example") CuishouEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_employee
     *
     * @mbggenerated Fri Apr 07 14:34:48 CST 2017
     */
    int updateByPrimaryKeySelective(CuishouEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_employee
     *
     * @mbggenerated Fri Apr 07 14:34:48 CST 2017
     */
    int updateByPrimaryKey(CuishouEmployee record);
}