package com.hotien.service.po;

import java.util.Date;

public class CuishouTaskAssign {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuishou_task_assign.id
     *
     * @mbggenerated Fri Apr 07 14:35:03 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuishou_task_assign.task_id
     *
     * @mbggenerated Fri Apr 07 14:35:03 CST 2017
     */
    private String taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuishou_task_assign.emp_id
     *
     * @mbggenerated Fri Apr 07 14:35:03 CST 2017
     */
    private String empId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuishou_task_assign.modify_time
     *
     * @mbggenerated Fri Apr 07 14:35:03 CST 2017
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuishou_task_assign.create_time
     *
     * @mbggenerated Fri Apr 07 14:35:03 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuishou_task_assign.del
     *
     * @mbggenerated Fri Apr 07 14:35:03 CST 2017
     */
    private String del;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuishou_task_assign.id
     *
     * @return the value of cuishou_task_assign.id
     *
     * @mbggenerated Fri Apr 07 14:35:03 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuishou_task_assign.id
     *
     * @param id the value for cuishou_task_assign.id
     *
     * @mbggenerated Fri Apr 07 14:35:03 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuishou_task_assign.task_id
     *
     * @return the value of cuishou_task_assign.task_id
     *
     * @mbggenerated Fri Apr 07 14:35:03 CST 2017
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuishou_task_assign.task_id
     *
     * @param taskId the value for cuishou_task_assign.task_id
     *
     * @mbggenerated Fri Apr 07 14:35:03 CST 2017
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuishou_task_assign.emp_id
     *
     * @return the value of cuishou_task_assign.emp_id
     *
     * @mbggenerated Fri Apr 07 14:35:03 CST 2017
     */
    public String getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuishou_task_assign.emp_id
     *
     * @param empId the value for cuishou_task_assign.emp_id
     *
     * @mbggenerated Fri Apr 07 14:35:03 CST 2017
     */
    public void setEmpId(String empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuishou_task_assign.modify_time
     *
     * @return the value of cuishou_task_assign.modify_time
     *
     * @mbggenerated Fri Apr 07 14:35:03 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuishou_task_assign.modify_time
     *
     * @param modifyTime the value for cuishou_task_assign.modify_time
     *
     * @mbggenerated Fri Apr 07 14:35:03 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuishou_task_assign.create_time
     *
     * @return the value of cuishou_task_assign.create_time
     *
     * @mbggenerated Fri Apr 07 14:35:03 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuishou_task_assign.create_time
     *
     * @param createTime the value for cuishou_task_assign.create_time
     *
     * @mbggenerated Fri Apr 07 14:35:03 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuishou_task_assign.del
     *
     * @return the value of cuishou_task_assign.del
     *
     * @mbggenerated Fri Apr 07 14:35:03 CST 2017
     */
    public String getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuishou_task_assign.del
     *
     * @param del the value for cuishou_task_assign.del
     *
     * @mbggenerated Fri Apr 07 14:35:03 CST 2017
     */
    public void setDel(String del) {
        this.del = del;
    }
}