package com.hotien.service.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CuishouUserRepayExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cuishou_user_repay
     *
     * @mbggenerated Fri Apr 07 14:35:43 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cuishou_user_repay
     *
     * @mbggenerated Fri Apr 07 14:35:43 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cuishou_user_repay
     *
     * @mbggenerated Fri Apr 07 14:35:43 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_user_repay
     *
     * @mbggenerated Fri Apr 07 14:35:43 CST 2017
     */
    public CuishouUserRepayExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_user_repay
     *
     * @mbggenerated Fri Apr 07 14:35:43 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_user_repay
     *
     * @mbggenerated Fri Apr 07 14:35:43 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_user_repay
     *
     * @mbggenerated Fri Apr 07 14:35:43 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_user_repay
     *
     * @mbggenerated Fri Apr 07 14:35:43 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_user_repay
     *
     * @mbggenerated Fri Apr 07 14:35:43 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_user_repay
     *
     * @mbggenerated Fri Apr 07 14:35:43 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_user_repay
     *
     * @mbggenerated Fri Apr 07 14:35:43 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_user_repay
     *
     * @mbggenerated Fri Apr 07 14:35:43 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_user_repay
     *
     * @mbggenerated Fri Apr 07 14:35:43 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_user_repay
     *
     * @mbggenerated Fri Apr 07 14:35:43 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cuishou_user_repay
     *
     * @mbggenerated Fri Apr 07 14:35:43 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andRepayTotalIsNull() {
            addCriterion("repay_total is null");
            return (Criteria) this;
        }

        public Criteria andRepayTotalIsNotNull() {
            addCriterion("repay_total is not null");
            return (Criteria) this;
        }

        public Criteria andRepayTotalEqualTo(Long value) {
            addCriterion("repay_total =", value, "repayTotal");
            return (Criteria) this;
        }

        public Criteria andRepayTotalNotEqualTo(Long value) {
            addCriterion("repay_total <>", value, "repayTotal");
            return (Criteria) this;
        }

        public Criteria andRepayTotalGreaterThan(Long value) {
            addCriterion("repay_total >", value, "repayTotal");
            return (Criteria) this;
        }

        public Criteria andRepayTotalGreaterThanOrEqualTo(Long value) {
            addCriterion("repay_total >=", value, "repayTotal");
            return (Criteria) this;
        }

        public Criteria andRepayTotalLessThan(Long value) {
            addCriterion("repay_total <", value, "repayTotal");
            return (Criteria) this;
        }

        public Criteria andRepayTotalLessThanOrEqualTo(Long value) {
            addCriterion("repay_total <=", value, "repayTotal");
            return (Criteria) this;
        }

        public Criteria andRepayTotalIn(List<Long> values) {
            addCriterion("repay_total in", values, "repayTotal");
            return (Criteria) this;
        }

        public Criteria andRepayTotalNotIn(List<Long> values) {
            addCriterion("repay_total not in", values, "repayTotal");
            return (Criteria) this;
        }

        public Criteria andRepayTotalBetween(Long value1, Long value2) {
            addCriterion("repay_total between", value1, value2, "repayTotal");
            return (Criteria) this;
        }

        public Criteria andRepayTotalNotBetween(Long value1, Long value2) {
            addCriterion("repay_total not between", value1, value2, "repayTotal");
            return (Criteria) this;
        }

        public Criteria andRepayCapitalIsNull() {
            addCriterion("repay_capital is null");
            return (Criteria) this;
        }

        public Criteria andRepayCapitalIsNotNull() {
            addCriterion("repay_capital is not null");
            return (Criteria) this;
        }

        public Criteria andRepayCapitalEqualTo(Long value) {
            addCriterion("repay_capital =", value, "repayCapital");
            return (Criteria) this;
        }

        public Criteria andRepayCapitalNotEqualTo(Long value) {
            addCriterion("repay_capital <>", value, "repayCapital");
            return (Criteria) this;
        }

        public Criteria andRepayCapitalGreaterThan(Long value) {
            addCriterion("repay_capital >", value, "repayCapital");
            return (Criteria) this;
        }

        public Criteria andRepayCapitalGreaterThanOrEqualTo(Long value) {
            addCriterion("repay_capital >=", value, "repayCapital");
            return (Criteria) this;
        }

        public Criteria andRepayCapitalLessThan(Long value) {
            addCriterion("repay_capital <", value, "repayCapital");
            return (Criteria) this;
        }

        public Criteria andRepayCapitalLessThanOrEqualTo(Long value) {
            addCriterion("repay_capital <=", value, "repayCapital");
            return (Criteria) this;
        }

        public Criteria andRepayCapitalIn(List<Long> values) {
            addCriterion("repay_capital in", values, "repayCapital");
            return (Criteria) this;
        }

        public Criteria andRepayCapitalNotIn(List<Long> values) {
            addCriterion("repay_capital not in", values, "repayCapital");
            return (Criteria) this;
        }

        public Criteria andRepayCapitalBetween(Long value1, Long value2) {
            addCriterion("repay_capital between", value1, value2, "repayCapital");
            return (Criteria) this;
        }

        public Criteria andRepayCapitalNotBetween(Long value1, Long value2) {
            addCriterion("repay_capital not between", value1, value2, "repayCapital");
            return (Criteria) this;
        }

        public Criteria andRepayServiceIsNull() {
            addCriterion("repay_service is null");
            return (Criteria) this;
        }

        public Criteria andRepayServiceIsNotNull() {
            addCriterion("repay_service is not null");
            return (Criteria) this;
        }

        public Criteria andRepayServiceEqualTo(Long value) {
            addCriterion("repay_service =", value, "repayService");
            return (Criteria) this;
        }

        public Criteria andRepayServiceNotEqualTo(Long value) {
            addCriterion("repay_service <>", value, "repayService");
            return (Criteria) this;
        }

        public Criteria andRepayServiceGreaterThan(Long value) {
            addCriterion("repay_service >", value, "repayService");
            return (Criteria) this;
        }

        public Criteria andRepayServiceGreaterThanOrEqualTo(Long value) {
            addCriterion("repay_service >=", value, "repayService");
            return (Criteria) this;
        }

        public Criteria andRepayServiceLessThan(Long value) {
            addCriterion("repay_service <", value, "repayService");
            return (Criteria) this;
        }

        public Criteria andRepayServiceLessThanOrEqualTo(Long value) {
            addCriterion("repay_service <=", value, "repayService");
            return (Criteria) this;
        }

        public Criteria andRepayServiceIn(List<Long> values) {
            addCriterion("repay_service in", values, "repayService");
            return (Criteria) this;
        }

        public Criteria andRepayServiceNotIn(List<Long> values) {
            addCriterion("repay_service not in", values, "repayService");
            return (Criteria) this;
        }

        public Criteria andRepayServiceBetween(Long value1, Long value2) {
            addCriterion("repay_service between", value1, value2, "repayService");
            return (Criteria) this;
        }

        public Criteria andRepayServiceNotBetween(Long value1, Long value2) {
            addCriterion("repay_service not between", value1, value2, "repayService");
            return (Criteria) this;
        }

        public Criteria andRepayAccrualIsNull() {
            addCriterion("repay_accrual is null");
            return (Criteria) this;
        }

        public Criteria andRepayAccrualIsNotNull() {
            addCriterion("repay_accrual is not null");
            return (Criteria) this;
        }

        public Criteria andRepayAccrualEqualTo(Long value) {
            addCriterion("repay_accrual =", value, "repayAccrual");
            return (Criteria) this;
        }

        public Criteria andRepayAccrualNotEqualTo(Long value) {
            addCriterion("repay_accrual <>", value, "repayAccrual");
            return (Criteria) this;
        }

        public Criteria andRepayAccrualGreaterThan(Long value) {
            addCriterion("repay_accrual >", value, "repayAccrual");
            return (Criteria) this;
        }

        public Criteria andRepayAccrualGreaterThanOrEqualTo(Long value) {
            addCriterion("repay_accrual >=", value, "repayAccrual");
            return (Criteria) this;
        }

        public Criteria andRepayAccrualLessThan(Long value) {
            addCriterion("repay_accrual <", value, "repayAccrual");
            return (Criteria) this;
        }

        public Criteria andRepayAccrualLessThanOrEqualTo(Long value) {
            addCriterion("repay_accrual <=", value, "repayAccrual");
            return (Criteria) this;
        }

        public Criteria andRepayAccrualIn(List<Long> values) {
            addCriterion("repay_accrual in", values, "repayAccrual");
            return (Criteria) this;
        }

        public Criteria andRepayAccrualNotIn(List<Long> values) {
            addCriterion("repay_accrual not in", values, "repayAccrual");
            return (Criteria) this;
        }

        public Criteria andRepayAccrualBetween(Long value1, Long value2) {
            addCriterion("repay_accrual between", value1, value2, "repayAccrual");
            return (Criteria) this;
        }

        public Criteria andRepayAccrualNotBetween(Long value1, Long value2) {
            addCriterion("repay_accrual not between", value1, value2, "repayAccrual");
            return (Criteria) this;
        }

        public Criteria andRepayOtherIsNull() {
            addCriterion("repay_other is null");
            return (Criteria) this;
        }

        public Criteria andRepayOtherIsNotNull() {
            addCriterion("repay_other is not null");
            return (Criteria) this;
        }

        public Criteria andRepayOtherEqualTo(Long value) {
            addCriterion("repay_other =", value, "repayOther");
            return (Criteria) this;
        }

        public Criteria andRepayOtherNotEqualTo(Long value) {
            addCriterion("repay_other <>", value, "repayOther");
            return (Criteria) this;
        }

        public Criteria andRepayOtherGreaterThan(Long value) {
            addCriterion("repay_other >", value, "repayOther");
            return (Criteria) this;
        }

        public Criteria andRepayOtherGreaterThanOrEqualTo(Long value) {
            addCriterion("repay_other >=", value, "repayOther");
            return (Criteria) this;
        }

        public Criteria andRepayOtherLessThan(Long value) {
            addCriterion("repay_other <", value, "repayOther");
            return (Criteria) this;
        }

        public Criteria andRepayOtherLessThanOrEqualTo(Long value) {
            addCriterion("repay_other <=", value, "repayOther");
            return (Criteria) this;
        }

        public Criteria andRepayOtherIn(List<Long> values) {
            addCriterion("repay_other in", values, "repayOther");
            return (Criteria) this;
        }

        public Criteria andRepayOtherNotIn(List<Long> values) {
            addCriterion("repay_other not in", values, "repayOther");
            return (Criteria) this;
        }

        public Criteria andRepayOtherBetween(Long value1, Long value2) {
            addCriterion("repay_other between", value1, value2, "repayOther");
            return (Criteria) this;
        }

        public Criteria andRepayOtherNotBetween(Long value1, Long value2) {
            addCriterion("repay_other not between", value1, value2, "repayOther");
            return (Criteria) this;
        }

        public Criteria andReduceFeeIsNull() {
            addCriterion("reduce_fee is null");
            return (Criteria) this;
        }

        public Criteria andReduceFeeIsNotNull() {
            addCriterion("reduce_fee is not null");
            return (Criteria) this;
        }

        public Criteria andReduceFeeEqualTo(Long value) {
            addCriterion("reduce_fee =", value, "reduceFee");
            return (Criteria) this;
        }

        public Criteria andReduceFeeNotEqualTo(Long value) {
            addCriterion("reduce_fee <>", value, "reduceFee");
            return (Criteria) this;
        }

        public Criteria andReduceFeeGreaterThan(Long value) {
            addCriterion("reduce_fee >", value, "reduceFee");
            return (Criteria) this;
        }

        public Criteria andReduceFeeGreaterThanOrEqualTo(Long value) {
            addCriterion("reduce_fee >=", value, "reduceFee");
            return (Criteria) this;
        }

        public Criteria andReduceFeeLessThan(Long value) {
            addCriterion("reduce_fee <", value, "reduceFee");
            return (Criteria) this;
        }

        public Criteria andReduceFeeLessThanOrEqualTo(Long value) {
            addCriterion("reduce_fee <=", value, "reduceFee");
            return (Criteria) this;
        }

        public Criteria andReduceFeeIn(List<Long> values) {
            addCriterion("reduce_fee in", values, "reduceFee");
            return (Criteria) this;
        }

        public Criteria andReduceFeeNotIn(List<Long> values) {
            addCriterion("reduce_fee not in", values, "reduceFee");
            return (Criteria) this;
        }

        public Criteria andReduceFeeBetween(Long value1, Long value2) {
            addCriterion("reduce_fee between", value1, value2, "reduceFee");
            return (Criteria) this;
        }

        public Criteria andReduceFeeNotBetween(Long value1, Long value2) {
            addCriterion("reduce_fee not between", value1, value2, "reduceFee");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("modify_time is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("modify_time =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("modify_time <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("modify_time >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modify_time >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("modify_time <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("modify_time <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("modify_time in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("modify_time not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("modify_time between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("modify_time not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andDelIsNull() {
            addCriterion("del is null");
            return (Criteria) this;
        }

        public Criteria andDelIsNotNull() {
            addCriterion("del is not null");
            return (Criteria) this;
        }

        public Criteria andDelEqualTo(String value) {
            addCriterion("del =", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelNotEqualTo(String value) {
            addCriterion("del <>", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelGreaterThan(String value) {
            addCriterion("del >", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelGreaterThanOrEqualTo(String value) {
            addCriterion("del >=", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelLessThan(String value) {
            addCriterion("del <", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelLessThanOrEqualTo(String value) {
            addCriterion("del <=", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelLike(String value) {
            addCriterion("del like", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelNotLike(String value) {
            addCriterion("del not like", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelIn(List<String> values) {
            addCriterion("del in", values, "del");
            return (Criteria) this;
        }

        public Criteria andDelNotIn(List<String> values) {
            addCriterion("del not in", values, "del");
            return (Criteria) this;
        }

        public Criteria andDelBetween(String value1, String value2) {
            addCriterion("del between", value1, value2, "del");
            return (Criteria) this;
        }

        public Criteria andDelNotBetween(String value1, String value2) {
            addCriterion("del not between", value1, value2, "del");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cuishou_user_repay
     *
     * @mbggenerated do_not_delete_during_merge Fri Apr 07 14:35:43 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cuishou_user_repay
     *
     * @mbggenerated Fri Apr 07 14:35:43 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}