package com.hotien.service.po;

import java.util.Date;

public class CuishouUserRepay {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuishou_user_repay.id
     *
     * @mbggenerated Fri Apr 07 14:35:43 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuishou_user_repay.user_id
     *
     * @mbggenerated Fri Apr 07 14:35:43 CST 2017
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuishou_user_repay.repay_total
     *
     * @mbggenerated Fri Apr 07 14:35:43 CST 2017
     */
    private Long repayTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuishou_user_repay.repay_capital
     *
     * @mbggenerated Fri Apr 07 14:35:43 CST 2017
     */
    private Long repayCapital;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuishou_user_repay.repay_service
     *
     * @mbggenerated Fri Apr 07 14:35:43 CST 2017
     */
    private Long repayService;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuishou_user_repay.repay_accrual
     *
     * @mbggenerated Fri Apr 07 14:35:43 CST 2017
     */
    private Long repayAccrual;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuishou_user_repay.repay_other
     *
     * @mbggenerated Fri Apr 07 14:35:43 CST 2017
     */
    private Long repayOther;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuishou_user_repay.reduce_fee
     *
     * @mbggenerated Fri Apr 07 14:35:43 CST 2017
     */
    private Long reduceFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuishou_user_repay.modify_time
     *
     * @mbggenerated Fri Apr 07 14:35:43 CST 2017
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuishou_user_repay.create_time
     *
     * @mbggenerated Fri Apr 07 14:35:43 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuishou_user_repay.del
     *
     * @mbggenerated Fri Apr 07 14:35:43 CST 2017
     */
    private String del;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuishou_user_repay.id
     *
     * @return the value of cuishou_user_repay.id
     *
     * @mbggenerated Fri Apr 07 14:35:43 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuishou_user_repay.id
     *
     * @param id the value for cuishou_user_repay.id
     *
     * @mbggenerated Fri Apr 07 14:35:43 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuishou_user_repay.user_id
     *
     * @return the value of cuishou_user_repay.user_id
     *
     * @mbggenerated Fri Apr 07 14:35:43 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuishou_user_repay.user_id
     *
     * @param userId the value for cuishou_user_repay.user_id
     *
     * @mbggenerated Fri Apr 07 14:35:43 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuishou_user_repay.repay_total
     *
     * @return the value of cuishou_user_repay.repay_total
     *
     * @mbggenerated Fri Apr 07 14:35:43 CST 2017
     */
    public Long getRepayTotal() {
        return repayTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuishou_user_repay.repay_total
     *
     * @param repayTotal the value for cuishou_user_repay.repay_total
     *
     * @mbggenerated Fri Apr 07 14:35:43 CST 2017
     */
    public void setRepayTotal(Long repayTotal) {
        this.repayTotal = repayTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuishou_user_repay.repay_capital
     *
     * @return the value of cuishou_user_repay.repay_capital
     *
     * @mbggenerated Fri Apr 07 14:35:43 CST 2017
     */
    public Long getRepayCapital() {
        return repayCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuishou_user_repay.repay_capital
     *
     * @param repayCapital the value for cuishou_user_repay.repay_capital
     *
     * @mbggenerated Fri Apr 07 14:35:43 CST 2017
     */
    public void setRepayCapital(Long repayCapital) {
        this.repayCapital = repayCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuishou_user_repay.repay_service
     *
     * @return the value of cuishou_user_repay.repay_service
     *
     * @mbggenerated Fri Apr 07 14:35:43 CST 2017
     */
    public Long getRepayService() {
        return repayService;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuishou_user_repay.repay_service
     *
     * @param repayService the value for cuishou_user_repay.repay_service
     *
     * @mbggenerated Fri Apr 07 14:35:43 CST 2017
     */
    public void setRepayService(Long repayService) {
        this.repayService = repayService;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuishou_user_repay.repay_accrual
     *
     * @return the value of cuishou_user_repay.repay_accrual
     *
     * @mbggenerated Fri Apr 07 14:35:43 CST 2017
     */
    public Long getRepayAccrual() {
        return repayAccrual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuishou_user_repay.repay_accrual
     *
     * @param repayAccrual the value for cuishou_user_repay.repay_accrual
     *
     * @mbggenerated Fri Apr 07 14:35:43 CST 2017
     */
    public void setRepayAccrual(Long repayAccrual) {
        this.repayAccrual = repayAccrual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuishou_user_repay.repay_other
     *
     * @return the value of cuishou_user_repay.repay_other
     *
     * @mbggenerated Fri Apr 07 14:35:43 CST 2017
     */
    public Long getRepayOther() {
        return repayOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuishou_user_repay.repay_other
     *
     * @param repayOther the value for cuishou_user_repay.repay_other
     *
     * @mbggenerated Fri Apr 07 14:35:43 CST 2017
     */
    public void setRepayOther(Long repayOther) {
        this.repayOther = repayOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuishou_user_repay.reduce_fee
     *
     * @return the value of cuishou_user_repay.reduce_fee
     *
     * @mbggenerated Fri Apr 07 14:35:43 CST 2017
     */
    public Long getReduceFee() {
        return reduceFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuishou_user_repay.reduce_fee
     *
     * @param reduceFee the value for cuishou_user_repay.reduce_fee
     *
     * @mbggenerated Fri Apr 07 14:35:43 CST 2017
     */
    public void setReduceFee(Long reduceFee) {
        this.reduceFee = reduceFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuishou_user_repay.modify_time
     *
     * @return the value of cuishou_user_repay.modify_time
     *
     * @mbggenerated Fri Apr 07 14:35:43 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuishou_user_repay.modify_time
     *
     * @param modifyTime the value for cuishou_user_repay.modify_time
     *
     * @mbggenerated Fri Apr 07 14:35:43 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuishou_user_repay.create_time
     *
     * @return the value of cuishou_user_repay.create_time
     *
     * @mbggenerated Fri Apr 07 14:35:43 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuishou_user_repay.create_time
     *
     * @param createTime the value for cuishou_user_repay.create_time
     *
     * @mbggenerated Fri Apr 07 14:35:43 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuishou_user_repay.del
     *
     * @return the value of cuishou_user_repay.del
     *
     * @mbggenerated Fri Apr 07 14:35:43 CST 2017
     */
    public String getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuishou_user_repay.del
     *
     * @param del the value for cuishou_user_repay.del
     *
     * @mbggenerated Fri Apr 07 14:35:43 CST 2017
     */
    public void setDel(String del) {
        this.del = del;
    }
}