package com.hotien.service.po;

import java.util.Date;

public class CuishouTask {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuishou_task.id
     *
     * @mbggenerated Fri Apr 07 14:33:12 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuishou_task.busi_type
     *
     * @mbggenerated Fri Apr 07 14:33:12 CST 2017
     */
    private String busiType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuishou_task.group
     *
     * @mbggenerated Fri Apr 07 14:33:12 CST 2017
     */
    private String group;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuishou_task.task_id
     *
     * @mbggenerated Fri Apr 07 14:33:12 CST 2017
     */
    private String taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuishou_task.user_id
     *
     * @mbggenerated Fri Apr 07 14:33:12 CST 2017
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuishou_task.state
     *
     * @mbggenerated Fri Apr 07 14:33:12 CST 2017
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuishou_task.overdue_days
     *
     * @mbggenerated Fri Apr 07 14:33:12 CST 2017
     */
    private Integer overdueDays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuishou_task.overdue_terms
     *
     * @mbggenerated Fri Apr 07 14:33:12 CST 2017
     */
    private Integer overdueTerms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuishou_task.modify_time
     *
     * @mbggenerated Fri Apr 07 14:33:12 CST 2017
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuishou_task.create_time
     *
     * @mbggenerated Fri Apr 07 14:33:12 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuishou_task.del
     *
     * @mbggenerated Fri Apr 07 14:33:12 CST 2017
     */
    private String del;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuishou_task.id
     *
     * @return the value of cuishou_task.id
     *
     * @mbggenerated Fri Apr 07 14:33:12 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuishou_task.id
     *
     * @param id the value for cuishou_task.id
     *
     * @mbggenerated Fri Apr 07 14:33:12 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuishou_task.busi_type
     *
     * @return the value of cuishou_task.busi_type
     *
     * @mbggenerated Fri Apr 07 14:33:12 CST 2017
     */
    public String getBusiType() {
        return busiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuishou_task.busi_type
     *
     * @param busiType the value for cuishou_task.busi_type
     *
     * @mbggenerated Fri Apr 07 14:33:12 CST 2017
     */
    public void setBusiType(String busiType) {
        this.busiType = busiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuishou_task.group
     *
     * @return the value of cuishou_task.group
     *
     * @mbggenerated Fri Apr 07 14:33:12 CST 2017
     */
    public String getGroup() {
        return group;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuishou_task.group
     *
     * @param group the value for cuishou_task.group
     *
     * @mbggenerated Fri Apr 07 14:33:12 CST 2017
     */
    public void setGroup(String group) {
        this.group = group;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuishou_task.task_id
     *
     * @return the value of cuishou_task.task_id
     *
     * @mbggenerated Fri Apr 07 14:33:12 CST 2017
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuishou_task.task_id
     *
     * @param taskId the value for cuishou_task.task_id
     *
     * @mbggenerated Fri Apr 07 14:33:12 CST 2017
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuishou_task.user_id
     *
     * @return the value of cuishou_task.user_id
     *
     * @mbggenerated Fri Apr 07 14:33:12 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuishou_task.user_id
     *
     * @param userId the value for cuishou_task.user_id
     *
     * @mbggenerated Fri Apr 07 14:33:12 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuishou_task.state
     *
     * @return the value of cuishou_task.state
     *
     * @mbggenerated Fri Apr 07 14:33:12 CST 2017
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuishou_task.state
     *
     * @param state the value for cuishou_task.state
     *
     * @mbggenerated Fri Apr 07 14:33:12 CST 2017
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuishou_task.overdue_days
     *
     * @return the value of cuishou_task.overdue_days
     *
     * @mbggenerated Fri Apr 07 14:33:12 CST 2017
     */
    public Integer getOverdueDays() {
        return overdueDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuishou_task.overdue_days
     *
     * @param overdueDays the value for cuishou_task.overdue_days
     *
     * @mbggenerated Fri Apr 07 14:33:12 CST 2017
     */
    public void setOverdueDays(Integer overdueDays) {
        this.overdueDays = overdueDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuishou_task.overdue_terms
     *
     * @return the value of cuishou_task.overdue_terms
     *
     * @mbggenerated Fri Apr 07 14:33:12 CST 2017
     */
    public Integer getOverdueTerms() {
        return overdueTerms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuishou_task.overdue_terms
     *
     * @param overdueTerms the value for cuishou_task.overdue_terms
     *
     * @mbggenerated Fri Apr 07 14:33:12 CST 2017
     */
    public void setOverdueTerms(Integer overdueTerms) {
        this.overdueTerms = overdueTerms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuishou_task.modify_time
     *
     * @return the value of cuishou_task.modify_time
     *
     * @mbggenerated Fri Apr 07 14:33:12 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuishou_task.modify_time
     *
     * @param modifyTime the value for cuishou_task.modify_time
     *
     * @mbggenerated Fri Apr 07 14:33:12 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuishou_task.create_time
     *
     * @return the value of cuishou_task.create_time
     *
     * @mbggenerated Fri Apr 07 14:33:12 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuishou_task.create_time
     *
     * @param createTime the value for cuishou_task.create_time
     *
     * @mbggenerated Fri Apr 07 14:33:12 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuishou_task.del
     *
     * @return the value of cuishou_task.del
     *
     * @mbggenerated Fri Apr 07 14:33:12 CST 2017
     */
    public String getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuishou_task.del
     *
     * @param del the value for cuishou_task.del
     *
     * @mbggenerated Fri Apr 07 14:33:12 CST 2017
     */
    public void setDel(String del) {
        this.del = del;
    }
}