package com.hotien.service.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CuishouUserOverdueExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cuishou_user_overdue
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cuishou_user_overdue
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cuishou_user_overdue
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_user_overdue
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    public CuishouUserOverdueExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_user_overdue
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_user_overdue
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_user_overdue
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_user_overdue
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_user_overdue
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_user_overdue
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_user_overdue
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_user_overdue
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_user_overdue
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuishou_user_overdue
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cuishou_user_overdue
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andOverdueTotalIsNull() {
            addCriterion("overdue_total is null");
            return (Criteria) this;
        }

        public Criteria andOverdueTotalIsNotNull() {
            addCriterion("overdue_total is not null");
            return (Criteria) this;
        }

        public Criteria andOverdueTotalEqualTo(Long value) {
            addCriterion("overdue_total =", value, "overdueTotal");
            return (Criteria) this;
        }

        public Criteria andOverdueTotalNotEqualTo(Long value) {
            addCriterion("overdue_total <>", value, "overdueTotal");
            return (Criteria) this;
        }

        public Criteria andOverdueTotalGreaterThan(Long value) {
            addCriterion("overdue_total >", value, "overdueTotal");
            return (Criteria) this;
        }

        public Criteria andOverdueTotalGreaterThanOrEqualTo(Long value) {
            addCriterion("overdue_total >=", value, "overdueTotal");
            return (Criteria) this;
        }

        public Criteria andOverdueTotalLessThan(Long value) {
            addCriterion("overdue_total <", value, "overdueTotal");
            return (Criteria) this;
        }

        public Criteria andOverdueTotalLessThanOrEqualTo(Long value) {
            addCriterion("overdue_total <=", value, "overdueTotal");
            return (Criteria) this;
        }

        public Criteria andOverdueTotalIn(List<Long> values) {
            addCriterion("overdue_total in", values, "overdueTotal");
            return (Criteria) this;
        }

        public Criteria andOverdueTotalNotIn(List<Long> values) {
            addCriterion("overdue_total not in", values, "overdueTotal");
            return (Criteria) this;
        }

        public Criteria andOverdueTotalBetween(Long value1, Long value2) {
            addCriterion("overdue_total between", value1, value2, "overdueTotal");
            return (Criteria) this;
        }

        public Criteria andOverdueTotalNotBetween(Long value1, Long value2) {
            addCriterion("overdue_total not between", value1, value2, "overdueTotal");
            return (Criteria) this;
        }

        public Criteria andOverdueCapitalIsNull() {
            addCriterion("overdue_capital is null");
            return (Criteria) this;
        }

        public Criteria andOverdueCapitalIsNotNull() {
            addCriterion("overdue_capital is not null");
            return (Criteria) this;
        }

        public Criteria andOverdueCapitalEqualTo(Long value) {
            addCriterion("overdue_capital =", value, "overdueCapital");
            return (Criteria) this;
        }

        public Criteria andOverdueCapitalNotEqualTo(Long value) {
            addCriterion("overdue_capital <>", value, "overdueCapital");
            return (Criteria) this;
        }

        public Criteria andOverdueCapitalGreaterThan(Long value) {
            addCriterion("overdue_capital >", value, "overdueCapital");
            return (Criteria) this;
        }

        public Criteria andOverdueCapitalGreaterThanOrEqualTo(Long value) {
            addCriterion("overdue_capital >=", value, "overdueCapital");
            return (Criteria) this;
        }

        public Criteria andOverdueCapitalLessThan(Long value) {
            addCriterion("overdue_capital <", value, "overdueCapital");
            return (Criteria) this;
        }

        public Criteria andOverdueCapitalLessThanOrEqualTo(Long value) {
            addCriterion("overdue_capital <=", value, "overdueCapital");
            return (Criteria) this;
        }

        public Criteria andOverdueCapitalIn(List<Long> values) {
            addCriterion("overdue_capital in", values, "overdueCapital");
            return (Criteria) this;
        }

        public Criteria andOverdueCapitalNotIn(List<Long> values) {
            addCriterion("overdue_capital not in", values, "overdueCapital");
            return (Criteria) this;
        }

        public Criteria andOverdueCapitalBetween(Long value1, Long value2) {
            addCriterion("overdue_capital between", value1, value2, "overdueCapital");
            return (Criteria) this;
        }

        public Criteria andOverdueCapitalNotBetween(Long value1, Long value2) {
            addCriterion("overdue_capital not between", value1, value2, "overdueCapital");
            return (Criteria) this;
        }

        public Criteria andOverdueServiceIsNull() {
            addCriterion("overdue_service is null");
            return (Criteria) this;
        }

        public Criteria andOverdueServiceIsNotNull() {
            addCriterion("overdue_service is not null");
            return (Criteria) this;
        }

        public Criteria andOverdueServiceEqualTo(Long value) {
            addCriterion("overdue_service =", value, "overdueService");
            return (Criteria) this;
        }

        public Criteria andOverdueServiceNotEqualTo(Long value) {
            addCriterion("overdue_service <>", value, "overdueService");
            return (Criteria) this;
        }

        public Criteria andOverdueServiceGreaterThan(Long value) {
            addCriterion("overdue_service >", value, "overdueService");
            return (Criteria) this;
        }

        public Criteria andOverdueServiceGreaterThanOrEqualTo(Long value) {
            addCriterion("overdue_service >=", value, "overdueService");
            return (Criteria) this;
        }

        public Criteria andOverdueServiceLessThan(Long value) {
            addCriterion("overdue_service <", value, "overdueService");
            return (Criteria) this;
        }

        public Criteria andOverdueServiceLessThanOrEqualTo(Long value) {
            addCriterion("overdue_service <=", value, "overdueService");
            return (Criteria) this;
        }

        public Criteria andOverdueServiceIn(List<Long> values) {
            addCriterion("overdue_service in", values, "overdueService");
            return (Criteria) this;
        }

        public Criteria andOverdueServiceNotIn(List<Long> values) {
            addCriterion("overdue_service not in", values, "overdueService");
            return (Criteria) this;
        }

        public Criteria andOverdueServiceBetween(Long value1, Long value2) {
            addCriterion("overdue_service between", value1, value2, "overdueService");
            return (Criteria) this;
        }

        public Criteria andOverdueServiceNotBetween(Long value1, Long value2) {
            addCriterion("overdue_service not between", value1, value2, "overdueService");
            return (Criteria) this;
        }

        public Criteria andOverdueAccrualIsNull() {
            addCriterion("overdue_accrual is null");
            return (Criteria) this;
        }

        public Criteria andOverdueAccrualIsNotNull() {
            addCriterion("overdue_accrual is not null");
            return (Criteria) this;
        }

        public Criteria andOverdueAccrualEqualTo(Long value) {
            addCriterion("overdue_accrual =", value, "overdueAccrual");
            return (Criteria) this;
        }

        public Criteria andOverdueAccrualNotEqualTo(Long value) {
            addCriterion("overdue_accrual <>", value, "overdueAccrual");
            return (Criteria) this;
        }

        public Criteria andOverdueAccrualGreaterThan(Long value) {
            addCriterion("overdue_accrual >", value, "overdueAccrual");
            return (Criteria) this;
        }

        public Criteria andOverdueAccrualGreaterThanOrEqualTo(Long value) {
            addCriterion("overdue_accrual >=", value, "overdueAccrual");
            return (Criteria) this;
        }

        public Criteria andOverdueAccrualLessThan(Long value) {
            addCriterion("overdue_accrual <", value, "overdueAccrual");
            return (Criteria) this;
        }

        public Criteria andOverdueAccrualLessThanOrEqualTo(Long value) {
            addCriterion("overdue_accrual <=", value, "overdueAccrual");
            return (Criteria) this;
        }

        public Criteria andOverdueAccrualIn(List<Long> values) {
            addCriterion("overdue_accrual in", values, "overdueAccrual");
            return (Criteria) this;
        }

        public Criteria andOverdueAccrualNotIn(List<Long> values) {
            addCriterion("overdue_accrual not in", values, "overdueAccrual");
            return (Criteria) this;
        }

        public Criteria andOverdueAccrualBetween(Long value1, Long value2) {
            addCriterion("overdue_accrual between", value1, value2, "overdueAccrual");
            return (Criteria) this;
        }

        public Criteria andOverdueAccrualNotBetween(Long value1, Long value2) {
            addCriterion("overdue_accrual not between", value1, value2, "overdueAccrual");
            return (Criteria) this;
        }

        public Criteria andOverdueOtherIsNull() {
            addCriterion("overdue_other is null");
            return (Criteria) this;
        }

        public Criteria andOverdueOtherIsNotNull() {
            addCriterion("overdue_other is not null");
            return (Criteria) this;
        }

        public Criteria andOverdueOtherEqualTo(Long value) {
            addCriterion("overdue_other =", value, "overdueOther");
            return (Criteria) this;
        }

        public Criteria andOverdueOtherNotEqualTo(Long value) {
            addCriterion("overdue_other <>", value, "overdueOther");
            return (Criteria) this;
        }

        public Criteria andOverdueOtherGreaterThan(Long value) {
            addCriterion("overdue_other >", value, "overdueOther");
            return (Criteria) this;
        }

        public Criteria andOverdueOtherGreaterThanOrEqualTo(Long value) {
            addCriterion("overdue_other >=", value, "overdueOther");
            return (Criteria) this;
        }

        public Criteria andOverdueOtherLessThan(Long value) {
            addCriterion("overdue_other <", value, "overdueOther");
            return (Criteria) this;
        }

        public Criteria andOverdueOtherLessThanOrEqualTo(Long value) {
            addCriterion("overdue_other <=", value, "overdueOther");
            return (Criteria) this;
        }

        public Criteria andOverdueOtherIn(List<Long> values) {
            addCriterion("overdue_other in", values, "overdueOther");
            return (Criteria) this;
        }

        public Criteria andOverdueOtherNotIn(List<Long> values) {
            addCriterion("overdue_other not in", values, "overdueOther");
            return (Criteria) this;
        }

        public Criteria andOverdueOtherBetween(Long value1, Long value2) {
            addCriterion("overdue_other between", value1, value2, "overdueOther");
            return (Criteria) this;
        }

        public Criteria andOverdueOtherNotBetween(Long value1, Long value2) {
            addCriterion("overdue_other not between", value1, value2, "overdueOther");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("modify_time is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("modify_time =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("modify_time <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("modify_time >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modify_time >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("modify_time <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("modify_time <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("modify_time in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("modify_time not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("modify_time between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("modify_time not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andDelIsNull() {
            addCriterion("del is null");
            return (Criteria) this;
        }

        public Criteria andDelIsNotNull() {
            addCriterion("del is not null");
            return (Criteria) this;
        }

        public Criteria andDelEqualTo(String value) {
            addCriterion("del =", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelNotEqualTo(String value) {
            addCriterion("del <>", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelGreaterThan(String value) {
            addCriterion("del >", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelGreaterThanOrEqualTo(String value) {
            addCriterion("del >=", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelLessThan(String value) {
            addCriterion("del <", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelLessThanOrEqualTo(String value) {
            addCriterion("del <=", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelLike(String value) {
            addCriterion("del like", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelNotLike(String value) {
            addCriterion("del not like", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelIn(List<String> values) {
            addCriterion("del in", values, "del");
            return (Criteria) this;
        }

        public Criteria andDelNotIn(List<String> values) {
            addCriterion("del not in", values, "del");
            return (Criteria) this;
        }

        public Criteria andDelBetween(String value1, String value2) {
            addCriterion("del between", value1, value2, "del");
            return (Criteria) this;
        }

        public Criteria andDelNotBetween(String value1, String value2) {
            addCriterion("del not between", value1, value2, "del");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cuishou_user_overdue
     *
     * @mbggenerated do_not_delete_during_merge Fri Apr 07 14:35:32 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cuishou_user_overdue
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}