package com.hotien.service.po;

import java.util.Date;

public class CuishouEmployee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuishou_employee.id
     *
     * @mbggenerated Fri Apr 07 14:34:48 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuishou_employee.emp_id
     *
     * @mbggenerated Fri Apr 07 14:34:48 CST 2017
     */
    private String empId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuishou_employee.emp_name
     *
     * @mbggenerated Fri Apr 07 14:34:48 CST 2017
     */
    private String empName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuishou_employee.telephone
     *
     * @mbggenerated Fri Apr 07 14:34:48 CST 2017
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuishou_employee.org_id
     *
     * @mbggenerated Fri Apr 07 14:34:48 CST 2017
     */
    private String orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuishou_employee.state
     *
     * @mbggenerated Fri Apr 07 14:34:48 CST 2017
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuishou_employee.modify_time
     *
     * @mbggenerated Fri Apr 07 14:34:48 CST 2017
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuishou_employee.create_time
     *
     * @mbggenerated Fri Apr 07 14:34:48 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuishou_employee.del
     *
     * @mbggenerated Fri Apr 07 14:34:48 CST 2017
     */
    private String del;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuishou_employee.id
     *
     * @return the value of cuishou_employee.id
     *
     * @mbggenerated Fri Apr 07 14:34:48 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuishou_employee.id
     *
     * @param id the value for cuishou_employee.id
     *
     * @mbggenerated Fri Apr 07 14:34:48 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuishou_employee.emp_id
     *
     * @return the value of cuishou_employee.emp_id
     *
     * @mbggenerated Fri Apr 07 14:34:48 CST 2017
     */
    public String getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuishou_employee.emp_id
     *
     * @param empId the value for cuishou_employee.emp_id
     *
     * @mbggenerated Fri Apr 07 14:34:48 CST 2017
     */
    public void setEmpId(String empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuishou_employee.emp_name
     *
     * @return the value of cuishou_employee.emp_name
     *
     * @mbggenerated Fri Apr 07 14:34:48 CST 2017
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuishou_employee.emp_name
     *
     * @param empName the value for cuishou_employee.emp_name
     *
     * @mbggenerated Fri Apr 07 14:34:48 CST 2017
     */
    public void setEmpName(String empName) {
        this.empName = empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuishou_employee.telephone
     *
     * @return the value of cuishou_employee.telephone
     *
     * @mbggenerated Fri Apr 07 14:34:48 CST 2017
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuishou_employee.telephone
     *
     * @param telephone the value for cuishou_employee.telephone
     *
     * @mbggenerated Fri Apr 07 14:34:48 CST 2017
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuishou_employee.org_id
     *
     * @return the value of cuishou_employee.org_id
     *
     * @mbggenerated Fri Apr 07 14:34:48 CST 2017
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuishou_employee.org_id
     *
     * @param orgId the value for cuishou_employee.org_id
     *
     * @mbggenerated Fri Apr 07 14:34:48 CST 2017
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuishou_employee.state
     *
     * @return the value of cuishou_employee.state
     *
     * @mbggenerated Fri Apr 07 14:34:48 CST 2017
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuishou_employee.state
     *
     * @param state the value for cuishou_employee.state
     *
     * @mbggenerated Fri Apr 07 14:34:48 CST 2017
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuishou_employee.modify_time
     *
     * @return the value of cuishou_employee.modify_time
     *
     * @mbggenerated Fri Apr 07 14:34:48 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuishou_employee.modify_time
     *
     * @param modifyTime the value for cuishou_employee.modify_time
     *
     * @mbggenerated Fri Apr 07 14:34:48 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuishou_employee.create_time
     *
     * @return the value of cuishou_employee.create_time
     *
     * @mbggenerated Fri Apr 07 14:34:48 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuishou_employee.create_time
     *
     * @param createTime the value for cuishou_employee.create_time
     *
     * @mbggenerated Fri Apr 07 14:34:48 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuishou_employee.del
     *
     * @return the value of cuishou_employee.del
     *
     * @mbggenerated Fri Apr 07 14:34:48 CST 2017
     */
    public String getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuishou_employee.del
     *
     * @param del the value for cuishou_employee.del
     *
     * @mbggenerated Fri Apr 07 14:34:48 CST 2017
     */
    public void setDel(String del) {
        this.del = del;
    }
}