package com.hotien.service.po;

import java.util.Date;

public class CuishouUserOverdue {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuishou_user_overdue.id
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuishou_user_overdue.user_id
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuishou_user_overdue.overdue_total
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    private Long overdueTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuishou_user_overdue.overdue_capital
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    private Long overdueCapital;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuishou_user_overdue.overdue_service
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    private Long overdueService;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuishou_user_overdue.overdue_accrual
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    private Long overdueAccrual;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuishou_user_overdue.overdue_other
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    private Long overdueOther;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuishou_user_overdue.modify_time
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuishou_user_overdue.create_time
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuishou_user_overdue.del
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    private String del;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuishou_user_overdue.id
     *
     * @return the value of cuishou_user_overdue.id
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuishou_user_overdue.id
     *
     * @param id the value for cuishou_user_overdue.id
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuishou_user_overdue.user_id
     *
     * @return the value of cuishou_user_overdue.user_id
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuishou_user_overdue.user_id
     *
     * @param userId the value for cuishou_user_overdue.user_id
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuishou_user_overdue.overdue_total
     *
     * @return the value of cuishou_user_overdue.overdue_total
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    public Long getOverdueTotal() {
        return overdueTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuishou_user_overdue.overdue_total
     *
     * @param overdueTotal the value for cuishou_user_overdue.overdue_total
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    public void setOverdueTotal(Long overdueTotal) {
        this.overdueTotal = overdueTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuishou_user_overdue.overdue_capital
     *
     * @return the value of cuishou_user_overdue.overdue_capital
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    public Long getOverdueCapital() {
        return overdueCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuishou_user_overdue.overdue_capital
     *
     * @param overdueCapital the value for cuishou_user_overdue.overdue_capital
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    public void setOverdueCapital(Long overdueCapital) {
        this.overdueCapital = overdueCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuishou_user_overdue.overdue_service
     *
     * @return the value of cuishou_user_overdue.overdue_service
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    public Long getOverdueService() {
        return overdueService;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuishou_user_overdue.overdue_service
     *
     * @param overdueService the value for cuishou_user_overdue.overdue_service
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    public void setOverdueService(Long overdueService) {
        this.overdueService = overdueService;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuishou_user_overdue.overdue_accrual
     *
     * @return the value of cuishou_user_overdue.overdue_accrual
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    public Long getOverdueAccrual() {
        return overdueAccrual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuishou_user_overdue.overdue_accrual
     *
     * @param overdueAccrual the value for cuishou_user_overdue.overdue_accrual
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    public void setOverdueAccrual(Long overdueAccrual) {
        this.overdueAccrual = overdueAccrual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuishou_user_overdue.overdue_other
     *
     * @return the value of cuishou_user_overdue.overdue_other
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    public Long getOverdueOther() {
        return overdueOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuishou_user_overdue.overdue_other
     *
     * @param overdueOther the value for cuishou_user_overdue.overdue_other
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    public void setOverdueOther(Long overdueOther) {
        this.overdueOther = overdueOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuishou_user_overdue.modify_time
     *
     * @return the value of cuishou_user_overdue.modify_time
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuishou_user_overdue.modify_time
     *
     * @param modifyTime the value for cuishou_user_overdue.modify_time
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuishou_user_overdue.create_time
     *
     * @return the value of cuishou_user_overdue.create_time
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuishou_user_overdue.create_time
     *
     * @param createTime the value for cuishou_user_overdue.create_time
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuishou_user_overdue.del
     *
     * @return the value of cuishou_user_overdue.del
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    public String getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuishou_user_overdue.del
     *
     * @param del the value for cuishou_user_overdue.del
     *
     * @mbggenerated Fri Apr 07 14:35:32 CST 2017
     */
    public void setDel(String del) {
        this.del = del;
    }
}